# Generated by Django 2.1.2 on 2018-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_profile_school_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_admin',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
