# Generated by Django 2.1.2 on 2019-01-14 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0010_profile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reservation Date')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Block')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Resource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('resource', 'block', 'date')},
        ),
    ]
