# Generated by Django 2.1.2 on 2019-01-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20190114_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.School'),
        ),
    ]
