# Generated by Django 2.1.2 on 2019-02-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20190201_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organzation',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.School', verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='school',
            name='organzation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Organization'),
        ),
    ]
