# Generated by Django 2.1.2 on 2019-02-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_auto_20190215_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Organization'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization_wide',
            field=models.BooleanField(default=False),
        ),
    ]
