# Generated by Django 2.1.2 on 2019-02-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_auto_20190215_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='organzation',
            new_name='organization',
        ),
    ]
