# Generated by Django 2.1.2 on 2018-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20181005_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_admin',
            field=models.BooleanField(default=None),
        ),
    ]
