# Generated by Django 2.1.2 on 2019-01-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20190131_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='organzation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Organization'),
        ),
    ]
