# Generated by Django 2.1.2 on 2019-02-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='owner',
        ),
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.School'),
            preserve_default=False,
        ),
    ]
