# Generated by Django 2.1.2 on 2019-02-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20190215_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(default='worcesterschools.net', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Organization'),
        ),
        migrations.AddField(
            model_name='email_filters',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Organization'),
        ),
    ]
