# Generated by Django 2.1.2 on 2019-02-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_auto_20190219_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='reservations.Resource'),
        ),
    ]
