# Generated by Django 2.1.2 on 2019-03-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_auto_20190306_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
    ]
