# Generated by Django 2.1.2 on 2019-03-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_auto_20190322_1323'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalsPerSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(default=0)),
                ('resources', models.IntegerField(default=0)),
                ('time_blocks', models.IntegerField(default=0)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.School')),
            ],
        ),
        migrations.RemoveField(
            model_name='totalusersperschool',
            name='school',
        ),
        migrations.DeleteModel(
            name='TotalUsersPerSchool',
        ),
    ]
